project:
  type: website
  output-dir: docs

website:
  title: "R for Data Science-Myanmar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - About me.qmd

format:
  html:
    theme: darkly
    mainfont: arial
    fontsize: 1.5rem
    monofont: courier new
    css: styles.css
    toc: true

editor: visual

